name: Documentation checks

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  linting:
    name: Documentation-quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install tox
      - run: tox
        env:
          TOXENV: docs
